SELECT
[account_number]
,[account type - cloud uk]
,[mi_mo - core]
,[mi_mo - managed]
,[mi_mo - mi]
,[mi_mo - mo]
,[mi_mo - unassigned]
,[tam_changed]
,[tam_ratio_changed]
,[tam_acct_ratio]
,[is_cloud_rackconnect_linked]
,[time_month_key]
,[target]
,[average_invoiced_last_12_months]
,[acc_tenure_in_months]
,[seasonal_control]
,[total_invoiced_in_month]
,[baseline_period_start]
,[total number of tickets]
,[avg days to close ticket]
,[avg minutes to first customer comment]
,[avg minutes to first racker comment]
,[avg minutes to started in progress]
,[avg minutes to started in progress - severity urgent]
,[num tickets severity - emergency]
,[number of tickets feedback received]
,[number of tickets solved]
,[rate of tickets feedback received]
,[rate of tickets solved]
,[number of commie tickets]
,[total invoiced in last 6 months]
,[avg per line item invoiced in last 6 months]
,[avg mthly num of invoiced items in last 6 months]
,[total invoiced in last 6 months vs prior 6 months]
,[avg invoiced in last 6 months vs prior 6 months]
,[avg mthly num of invoiced items in last 6 months vs prior 6 months]
,[total invoiced in last 3 months vs prior 3 months]
,[avg invoiced in last 3 months vs prior 3 months]
,[avg mthly num of invoiced items in last 3 months vs prior 3 months]
,[per unit price - next gen servers]
,[per unit price - cloud block storage]
,[per unit price - cloud files]
,[per unit price - first gen servers]
,[per unit price - cloud load balancer]
,[per unit price - cloud sites]
,[per unit price - cloud backup]
,[per unit price - total outgoing bw]
,[per unit price - cloud monitoring]
,[per unit price - cloud databases]
,[per unit price - cloud queues]
,[how many units - next gen servers]
,[how many units - cloud block storage]
,[how many units - cloud files]
,[how many units - first gen servers]
,[how many units - cloud load balancer]
,[how many units - cloud sites]
,[how many units - cloud backup]
,[how many units - total outgoing bw]
,[how many units - cloud monitoring]
,[how many units - cloud databases]
,[how many units - cloud queues]
,[pct of invoice - next gen servers]
,[pct of invoice - cloud block storage]
,[pct of invoice - cloud files]
,[pct of invoice - first gen servers]
,[pct of invoice - cloud load balancer]
,[pct of invoice - cloud sites]
,[pct of invoice - cloud backup]
,[pct of invoice - total outgoing bw]
,[pct of invoice - cloud monitoring]
,[pct of invoice - cloud databases]
,[pct of invoice - cloud queues]
,[Num Opportunities Last 6 Months]
,[Num Opportunities Won Last 6 Months]
,[Num Opportunities Lost Last 6 Months]
,[Pct Opportunities Won Last 6 Months]
,[Pct Opportunities Lost Last 6 Months]
,[Num Opportunities Last 3 Months]
,[Num Opportunities Won Last 3 Months]
,[Num Opportunities Lost Last 3 Months]
,[Pct Opportunities Won Last 3 Months]
,[Pct Opportunities Lost Last 3 Months]
,[Total Value of Opportunities Last 6 Months]
,[Total Value of Opportunities Last 3 Months]
,[Average Value of Opportunities Last 6 Months]
,[Average Value of Opportunities Last 3 Months]
,[Num Opportunities]
,[Num Opps ALLOW_QUOTE - Not Allowed]
,[Num Opps ALLOW_QUOTE - Allowed]
,[Num Opps BUCKET_INFLUENCE - NULL]
,[Num Opps BUCKET_INFLUENCE - Marketing]
,[Num Opps BUCKET_SOURCE - Sales]
,[Num Opps BUCKET_SOURCE - NULL]
,[Num Opps BUCKET_SOURCE - Marketing]
,[Num Opps CATEGORY - Upgrade]
,[Num Opps CATEGORY - New]
,[Num Opps CATEGORY - New Footprint]
,[Num Opps CATEGORY - Cloud Net Revenue]
,[Num Opps CATEGORY - New Logo]
,[Num Opps CATEGORY - Migration]
,[Num Opps CATEGORY - NULL]
,[Num Opps COMMISSION_ROLE - NULL]
,[Num Opps COMMISSION_ROLE - Pay Commissions]
,[Num Opps COMPETITORS - NULL]
,[Num Opps COMPETITORS - In-house]
,[Num Opps COMPETITORS - Other]
,[Num Opps CONTRACT_LENGTH - NULL]
,[Num Opps CONTRACT_LENGTH - 12]
,[Num Opps CONTRACT_LENGTH - 1]
,[Num Opps CONTRACT_LENGTH - 0]
,[Num Opps CONTRACT_LENGTH - 24]
,[Num Opps CVP_VERIFIED - FALSE]
,[Num Opps CVP_VERIFIED - TRUE]
,[Num Opps DATA_QUALITY_DESCRIPTION - Missing: Lead Source, Next Ste]
,[Num Opps DATA_QUALITY_DESCRIPTION - Missing: Amount, Next Steps]
,[Num Opps DATA_QUALITY_DESCRIPTION - Missing: Next Steps]
,[Num Opps DATA_QUALITY_DESCRIPTION - Missing: Lead Source]
,[Num Opps DATA_QUALITY_DESCRIPTION - All Opportunity Details Captur]
,[Num Opps DATA_QUALITY_DESCRIPTION - Missing: Amount]
,[Num Opps DATA_QUALITY_SCORE - 60]
,[Num Opps DATA_QUALITY_SCORE - 40]
,[Num Opps DATA_QUALITY_SCORE - 80]
,[Num Opps DATA_QUALITY_SCORE - 100]
,[Num Opps ECONNECT_RECEIVED - FALSE]
,[Num Opps ECONNECT_RECEIVED - TRUE]
,[Num Opps FOCUS_AREA - NULL]
,[Num Opps FOCUS_AREA - Dedicated]
,[Num Opps FOCUS_AREA - Cloud Office]
,[Num Opps FOCUS_AREA - OpenStack Public]
,[Num Opps FOCUS_AREA - TriCore]
,[Num Opps FOCUS_AREA - Amazon]
,[Num Opps FORECASTCATEGORY - Closed]
,[Num Opps FORECASTCATEGORY - Omitted]
,[Num Opps FORECASTCATEGORY - Pipeline]
,[Num Opps FORECASTCATEGORYNAME - Closed]
,[Num Opps FORECASTCATEGORYNAME - Omitted]
,[Num Opps FORECASTCATEGORYNAME - Pipeline]
,[Num Opps ISWON - TRUE]
,[Num Opps ISWON - FALSE]
,[Num Opps LEADSOURCE - NULL]
,[Num Opps LEADSOURCE - Chat]
,[Num Opps LEADSOURCE - Call In]
,[Num Opps LEADSOURCE - Partner Network]
,[Num Opps LEADSOURCE - Outbound]
,[Num Opps LEADSOURCE - Site Submission]
,[Num Opps LEADSOURCE - Unknown]
,[Num Opps LIVE_CALL - FALSE]
,[Num Opps MARKET_SOURCE - NULL]
,[Num Opps MARKET_SOURCE - No]
,[Num Opps MARKET_SOURCE - Yes]
,[Num Opps NUTCASE_DEAL_PROBABILITY - 0]
,[Num Opps ON_DEMAND_RECONCILED - FALSE]
,[Num Opps ON_DEMAND_RECONCILED - TRUE]
,[Num Opps PAIN_POINT - NULL]
,[Num Opps PAIN_POINT - Other]
,[Num Opps PAIN_POINT - ServiceNow]
,[Num Opps PROBABILITY - 100]
,[Num Opps PROBABILITY - 0]
,[Num Opps PROBABILITY - 15]
,[Num Opps REQUESTED_PRODUCTS - NULL]
,[Num Opps REQUESTED_PRODUCTS - Hosting Only]
,[Num Opps SUPPORT_UNIT - NULL]
,[Num Opps SUPPORT_UNIT - TriCore]
,[Num Opps SUPPORT_UNIT - Enterprise]
,[Num Opps SUPPORT_UNIT - SMB]
,[Num Opps SUPPORT_UNIT - Email & Apps]
,[Num Opps TICKET_TYPE - NULL]
,[Num Opps TICKET_TYPE - Upgrade]
,[Num Opps TYPEX - Dedicated/Private Cloud]
,[Num Opps TYPEX - Revenue Ticket]
,[Num Opps TYPEX - Mail Contract Signup]
,[Num Opps TYPEX - Rackspace Cloud]
,[Num Opps TYPEX - TriCore]
,[Num Opps TYPEX - AWS]
,[Num Opps WHAT_DID_WE_DO_WELL - NULL]
,[Num Opps WHAT_DID_WE_DO_WELL - Solution Fit]
,[Num Opps WHY_DID_WE_LOSE - NULL]
,[Num Opps WHY_DID_WE_LOSE - No Response]
,[Num Opps WHY_DID_WE_LOSE - Unresponsive]
,[Num Opps WHY_DID_WE_LOSE - Project Abandoned]
,[Num Opps WHY_DID_WE_LOSE - Existing Opp/Closed via Ticket]
,[Num Opps WHY_DID_WE_LOSE - Price]
,CASE WHEN Account_SLA_Type IS NULL  then 0
WHEN Account_SLA_Type ='None'  then 0
WHEN Account_SLA_Type ='Standard' then 1
WHEN Account_SLA_Type ='Gold' then 2
WHEN Account_SLA_Type ='Platinum' then 3
end as Account_SLA_Type_num
,[num distinct account_team_name]
,[num distinct account_manager]
,[num distinct account_bdc]
,[num distinct account_primary_contact]
,[num distinct account_region]
,[num distinct account_billing_street]
,[num distinct account_billing_city]
,[num distinct account_billing_state]
,[num distinct account_billing_postal_code]
,[num distinct account_billing_country]
,[num distinct account_geographic_location]
,[last_survey_score]
,[second_last_survey_score]
,[change_in_survey_score]
,[rating_promoter_to_promoter]
,[rating_promoter_to_passive]
,[rating_promoter_to_detractor]
,[rating_passive_to_promoter]
,[rating_passive_to_passive]
,[rating_passive_to_detractor]
,[rating_detractor_to_promoter]
,[rating_detractor_to_passive]
,[rating_detractor_to_detractor]
,[ownership - private]
,[ownership - public]
,[ownership - unknown]
,[ownership - subsidiary]
,[ownership - other]
,[site - branch]
,[site - headquarters]
,[site - single location]
,[company_review_priority]
,[number_of_customer_accounts]
,[number_of_cloud_accounts]
FROM [CustomerRetention].[dbo].[AMT_FINAL_AMT_cloud_live_allvariables] with (nolock)
