select
account_number
,time_month_key
,time_month_key_dt
,account_name
,average_invoiced_last_12_months
,revenue_segment
,avg_monthly_invoice_band
,churn_flag
,target
,pct_change
,first_churn_tmk
,total_invoiced_in_month
,average_invoiced_next_6_months
,num_months_last_12_months
,num_months_next_6_months
,month_order
,month_order_desc
,time_month_key_eo_last_month_dt
,account_type_cloud_uk
,account_segment
,account_sub_type
,case when account_sla_type is null  then 0
when account_sla_type ='none'  then 0
when account_sla_type ='standard' then 1
when account_sla_type ='gold' then 2
when account_sla_type ='platinum' then 3
end as account_sla_type_num
,average_value_of_opportunities_last_3_months
,average_value_of_opportunities_last_6_months
,avg_invoiced_in_last_3_months_vs_prior_3_months
,avg_invoiced_in_last_6_months_vs_prior_6_months
,avg_mthly_num_of_invoiced_items_in_last_6_months
,avg_per_line_item_invoiced_in_last_6_months
,avg_unit_price_cloud_backup
,avg_unit_price_cloud_block_storage
,avg_unit_price_cloud_databases
,avg_unit_price_cloud_files
,avg_unit_price_cloud_load_balancer
,avg_unit_price_cloud_monitoring
,avg_unit_price_cloud_queues
,avg_unit_price_cloud_sites
,avg_unit_price_first_gen_servers
,avg_unit_price_next_gen_servers
,avg_unit_price_total_outgoing_bw
,change_in_survey_score
,case when does_account_have_cloud_block_storage='y' then 1 else 0 end as does_account_have_cloud_block_storage
,case when does_account_have_cloud_files='y' then 1 else 0 end as does_account_have_cloud_files
,case when does_account_have_next_gen_servers='y' then 1 else 0 end as does_account_have_next_gen_servers
,how_many_units_cloud_backup
,how_many_units_cloud_block_storage
,how_many_units_cloud_databases
,how_many_units_cloud_files
,how_many_units_cloud_load_balancer
,how_many_units_cloud_monitoring
,how_many_units_cloud_queues
,how_many_units_cloud_sites
,how_many_units_first_gen_servers
,how_many_units_next_gen_servers
,how_many_units_total_outgoing_bw
,is_cloud_rackconnect_linked
--,last_survey_rating_original
,last_survey_responseflag
,last_survey_score
--,mi_mo
,mi_mo_core
,mi_mo_managed
,mi_mo_mi
,mi_mo_mo
,mi_mo_unassigned
,num_distinct_account_bdc
,num_distinct_account_billing_city
,num_distinct_account_billing_country
,num_distinct_account_billing_postal_code
,num_distinct_account_billing_state
,num_distinct_account_billing_street
,num_distinct_account_business_type
,num_distinct_account_geographic_location
,num_distinct_account_manager
,num_distinct_account_primary_contact
,num_distinct_account_region
,num_distinct_account_sla_type
,num_distinct_account_team_name
,num_opportunities_last_12_months
,num_opportunities_last_3_months
,num_opportunities_last_6_months
,num_opportunities_lost_last_3_months
,num_opportunities_lost_last_6_months
,num_opportunities_won_last_3_months
,num_opportunities_won_last_6_months
,num_opps_allow_quote_allowed
,num_opps_allow_quote_not_allowed
,num_opps_bucket_influence_marketing
,num_opps_bucket_influence_null
,num_opps_bucket_source_marketing
,num_opps_bucket_source_null
,num_opps_bucket_source_sales
,num_opps_category_cloud_net_revenue
,num_opps_category_migration
,num_opps_category_new
,num_opps_category_new_footprint
,num_opps_category_new_logo
,num_opps_category_null
,num_opps_category_upgrade
,num_opps_commission_role_null
,num_opps_commission_role_pay_commissions
,num_opps_competitors_in_house
,num_opps_competitors_null
,num_opps_competitors_other
,num_opps_contract_length_0
,num_opps_contract_length_1
,num_opps_contract_length_12
,num_opps_contract_length_24
,num_opps_contract_length_null
,num_opps_cvp_verified_false
,num_opps_cvp_verified_true
,num_opps_data_quality_description_all_opportunity_details_captur
,num_opps_data_quality_description_missing_amount
,num_opps_data_quality_description_missing_amount_lead_source
,num_opps_data_quality_description_missing_amount_next_steps
,num_opps_data_quality_description_missing_lead_source
,num_opps_data_quality_description_missing_lead_source_next_ste
,num_opps_data_quality_description_missing_next_steps
,num_opps_data_quality_score_100
,num_opps_data_quality_score_40
,num_opps_data_quality_score_60
,num_opps_data_quality_score_80
,num_opps_econnect_received_false
,num_opps_econnect_received_true
,num_opps_focus_area_amazon
,num_opps_focus_area_cloud_office
,num_opps_focus_area_dedicated
,num_opps_focus_area_null
,num_opps_focus_area_openstack_public
,num_opps_focus_area_tricore
,num_opps_forecastcategory_closed
,num_opps_forecastcategory_omitted
,num_opps_forecastcategory_pipeline
,num_opps_forecastcategoryname_closed
,num_opps_forecastcategoryname_omitted
,num_opps_forecastcategoryname_pipeline
,num_opps_iswon_false
,num_opps_iswon_true
,num_opps_leadsource_call_in
,num_opps_leadsource_chat
,num_opps_leadsource_null
,num_opps_leadsource_outbound
,num_opps_leadsource_partner_network
,num_opps_leadsource_site_submission
,num_opps_leadsource_unknown
,num_opps_live_call_false
,num_opps_market_source_no
,num_opps_market_source_null
,num_opps_market_source_yes
,num_opps_nutcase_deal_probability_0
,num_opps_on_demand_reconciled_false
,num_opps_on_demand_reconciled_true
,num_opps_pain_point_null
,num_opps_pain_point_other
,num_opps_pain_point_servicenow
,num_opps_probability_0
,num_opps_probability_100
,num_opps_probability_15
,num_opps_requested_products_hosting_only
,num_opps_requested_products_null
,num_opps_support_unit_email_apps
,num_opps_support_unit_enterprise
,num_opps_support_unit_null
,num_opps_support_unit_smb
,num_opps_support_unit_tricore
,num_opps_ticket_type_null
,num_opps_ticket_type_upgrade
,num_opps_typex_aws
,num_opps_typex_dedicated_private_cloud
,num_opps_typex_mail_contract_signup
,num_opps_typex_rackspace_cloud
,num_opps_typex_revenue_ticket
,num_opps_typex_tricore
,num_opps_what_did_we_do_well_null
,num_opps_what_did_we_do_well_solution_fit
,num_opps_why_did_we_lose_existing_opp_closed_via_ticket
,num_opps_why_did_we_lose_no_response
,num_opps_why_did_we_lose_null
,num_opps_why_did_we_lose_price
,num_opps_why_did_we_lose_project_abandoned
,num_opps_why_did_we_lose_unresponsive
,number_of_cloud_accounts
,number_of_customer_accounts
,ownership_other
,ownership_private
,ownership_public
,ownership_subsidiary
,ownership_unknown
,pct_of_invoice_cloud_backup
,pct_of_invoice_cloud_block_storage
,pct_of_invoice_cloud_databases
,pct_of_invoice_cloud_files
,pct_of_invoice_cloud_load_balancer
,pct_of_invoice_cloud_monitoring
,pct_of_invoice_cloud_queues
,pct_of_invoice_cloud_sites
,pct_of_invoice_first_gen_servers
,pct_of_invoice_next_gen_servers
,pct_of_invoice_total_outgoing_bw
,pct_opportunities_lost_last_3_months
,pct_opportunities_lost_last_6_months
,pct_opportunities_won_last_3_months
,pct_opportunities_won_last_6_months
,rating_detractor_to_detractor
,rating_detractor_to_passive
,rating_detractor_to_promoter
,rating_passive_to_detractor
,rating_passive_to_passive
,rating_passive_to_promoter
,rating_promoter_to_detractor
,rating_promoter_to_passive
,rating_promoter_to_promoter
,ratio_mthly_num_of_invoiced_items_in_last_3_months_vs_prior_3_months
,ratio_mthly_num_of_invoiced_items_in_last_6_months_vs_prior_6_months
,seasonal_control
--,second_last_survey_rating_original
,second_last_survey_responseflag
,second_last_survey_score
,site_branch
,site_headquarters
,site_single_location
,tam_acct_ratio
,tam_changed
,tam_ratio_changed
,total_invoiced_in_last_3_months_vs_prior_3_months
,total_invoiced_in_last_6_months
,total_invoiced_in_last_6_months_vs_prior_6_months
,total_value_of_opportunities_last_3_months
,total_value_of_opportunities_last_6_months
from [customerretention].[dbo].[00final_cloud] with (nolock)
where time_month_key = (select max(time_month_key) from customerretention.dbo.[00final_cloud])